dvfjdsfvjd

diff --git a/.github/workflows/terraform-kubespray.yaml b/.github/workflows/terraform-kubespray.yaml
--- a/.github/workflows/terraform-kubespray.yaml
+++ b/.github/workflows/terraform-kubespray.yaml
@@ -24,24 +24,23 @@ jobs:
         ls -lrt terraform/
         ls -lrt kubespray/
         
-Comment: >
-    - name: Setup Terrafrom
-      uses: hashicorp/setup-terraform@v1
-    - name: Terraform Format
-      id: fmt
-      run: terraform fmt -check
-    - name: Terraform Init
-      id: init
-      run: terraform init
-    - name: Terraform Validate
-      id: validate
-      run: terraform validate -no-color
-    - name: Terraform Plan
-      id: plan
-      run: terraform plan -no-color -input=false
-      continue-on-error: true
-    - name: Terraform Plan Status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
-    - name: Terraform Apply
-      run: terraform apply -auto-approve -input=false
+    # - name: Setup Terrafrom
+    #   uses: hashicorp/setup-terraform@v1
+    # - name: Terraform Format
+    #   id: fmt
+    #   run: terraform fmt -check
+    # - name: Terraform Init
+    #   id: init
+    #   run: terraform init
+    # - name: Terraform Validate
+    #   id: validate
+    #   run: terraform validate -no-color
+    # - name: Terraform Plan
+    #   id: plan
+    #   run: terraform plan -no-color -input=false
+    #   continue-on-error: true
+    # - name: Terraform Plan Status
+    #   if: steps.plan.outcome == 'failure'
+    #   run: exit 1
+    # - name: Terraform Apply
+    #   run: terraform apply -auto-approve -input=false
